### PR TITLE
Loading prebuilt pickle file

### PR DESCRIPTION
**Pull request by wassimseif**
`def build_dict` takes around 30 mins to finish. This patch will just check if the pickle file is already there so it doesn't build it again

### CODE REVIEW

**Comment by dongjun-Lee** [comment]
Hello. Thank you for your PR. However, [this commit](https://github.com/dongjun-Lee/text-summarization-tensorflow/pull/9/commits/ad54856e8b249aa575a019148fac09d310e50844) will generate an error when there is no pre-trained ```word_dict.pickle```.  I think [this way](https://github.com/dongjun-Lee/text-classification-models-tf/blob/master/data_utils.py#L32-L54) would be better.

**Comment by wassimseif** [comment]
Hello
I added the check is the file exists. Also, I noticed that the `build_dataset` function takes time. any ideas how can we do the same for it?

**Comment by dongjun-Lee** [comment]
Saving [```train_x```, ```train_y```](https://github.com/dongjun-Lee/text-summarization-tensorflow/blob/master/train.py#L36), [```valid_x```, ```valid_y```](https://github.com/dongjun-Lee/text-summarization-tensorflow/blob/master/test.py#L13) with ```pickle``` might help.

**Comment by wassimseif** [comment]
Will do. btw I'm curious on which GPU did you train this. on a 1080 it's struggling

**Comment by dongjun-Lee** [comment]
I used two TITAN Xp and it takes a long time for me too.

**Comment by wassimseif** [comment]
tick tock

**Pull request closed without merging**
